version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
  consul:
    command: -server -bootstrap -advertise 10.0.2.15
    image: progrium/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  registrator:
    command: -ip=10.0.2.15 consul://consul:8500
    image: gliderlabs/registrator:latest
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    